#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

#define MAX_STRING 50
#define MAX_ESTUDANTES 100
#define MAX_NUMERO_ESTUDANTE 9999
#define MIN_NUMERO_ESTUDANTE 1
#define MAX_NOTA 20
#define MIN_NOTA 0


#endif // CONSTANTES_H_INCLUDED
